### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by minhnimble** [Thieurom/NimbleSurvey#14]
Hello Thieu 👋 , thank you for your effort on the code submission. I am Mikey, acting as an Engineer Lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process and I would love to hear back from you as well. Therefore, don’t hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue here and you’d like to correct them, please address the issue using a proper git-flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready) and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs, I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us right away so that we can plan accordingly.

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by minhnimble** [comment]
Hi, Thieu 👋

I completed the 1st round of review just now. Please go ahead and let me know your thoughts on the proposed issues. 

Have a great day!

**Comment by Thieurom** [comment]
Hi Minh!

I've resolved about two-thirds of your issues, all are very valuable to me. Please take your time to check.
Any further feedback would be appreciated!

I'll try to complete the remaining within tomorrow (Fri, June 20).

Thanks!

**Comment by minhnimble** [comment]
Hello, Thieu 👋

Thanks for the progress update! It looks good to me with your plan 👍

By the way, I notice for some of your pull requests, you added the discussion directly in the PRs. Unfortunately, this actually hard for us to continue the discussion as we will need to switch back and forth between the issue and its corresponding pull request(s). Do you mind bringing the discussion and each individual issue fixing status onto each issue directly? thanks 🙏

**Comment by minhnimble** [comment]
I also complete the 2nd round of review just now. Again, you can start providing your feedback on all the new comments and remaining issues at this point.

Have a great afternoon! ☀️

**Comment by Thieurom** [comment]
Hi Minh,

I just had commented on the following issues: cover image resolution, handle tapping on page indicator, show a correct error message when failing to login.
May I ask for 2 more days to resolve the remaining and your new comments? I got to work this Saturday so I'll manage to work on these ones on Sunday.

Hope you accept and have a nice weekend!

**Comment by Thieurom** [comment]
I completed resolving (by code changes and discussion) all your issues. Please take your time to check, and provide any suggestions to continue improving. Really thanks!

**Comment by minhnimble** [comment]
Good morning, Thieu ☀️

Thank you for your timely updates! As of this point, my review for this code challenge session reaches to a conclusion and thus no more submission will be needed from your end. For the next step, you will be hearing from the Talent Acquisition team about the decision as soon as possible. 🙏

In the end, it was a good pleasure reviewing your code and getting to know you, you have performed well. 👍 I wish you all the very best. 🍀

**Comment by Thieurom** [comment]
Thank you for your kind words, Minh!

It was a pleasure for me too as I really enjoyed the review process and learned a lot.
Thanks again!
