### ISSUE TITLE
[Feature] Handle when there is an error from the API on Login screen

### ISSUE THREAD

**Issue by minhnimble** [Thieurom/NimbleSurvey#16]
## Issue

When the user provides an invalid combination of email and password or attempts to login the application without any connection, there is no handling or a visible prompt on the application to let the user knows what is currently happening. As a result, it is quite confusing for the user on what to do next for logging in successfully.

- Provide an invalid combination of email and password:

https://user-images.githubusercontent.com/70877098/168978861-2b5d407c-6b83-49c2-9e2f-7872bccaf3b6.mp4

## Expect

Error cases should be visibly handled on the application and let the user knows what is happening.

**Comment by minhnimble** [comment]
After checking your fix on the case when there is no internet connection and valid email/password are provided, the error message about wrong password or email is shown instead. As a result, a wrong type of error is shown and the user is unable to process further following the error prompt. 

https://user-images.githubusercontent.com/70877098/169450000-b42c56a8-d3f2-4a82-9a4e-e73b292d81bc.MP4

**Comment by Thieurom** [comment]
@minhnimble This issue was fixed by PR #30 
Please take your time to verify.
