### ISSUE TITLE
[Bug] Starting the app without the internet connection will stuck at a black screen forever

### ISSUE THREAD

**Issue by minhnimble** [Thieurom/NimbleSurvey#17]
## Issue

When starting the application without the internet connection, if there is a previous logged session, the user will see a black screen without any message. Turning the internet connection back online does nothing and the application is stuck there forever.

## Expect

When starting the application without the internet connection, if there is a previous logged session, there should be an option for the user to retry to reload the data instead of blocking the user forever with a black screen.

## Step to reproduce

https://user-images.githubusercontent.com/70877098/168980471-8f72b922-afa9-46af-8a89-aa510eddaace.MP4

**Comment by Thieurom** [comment]
This has been resolved by PR #31 by presenting users an option to reload data when the Home screen fails to load the first page.
 
![Simulator Screen Shot - iPhone 13 - 2022-05-22 at 11 16 45](https://user-images.githubusercontent.com/17972674/169679350-26312464-7310-4fb0-ba8f-72770279089a.png)
