### ISSUE TITLE
[Feature] Support pagination loading

### ISSUE THREAD

**Issue by minhnimble** [Thieurom/NimbleSurvey#18]
## Issue

As you can probably see from the Postman, the surveys list API should be capable of providing more data than what the application currently displays. Right now the data shown on the Surveys List screen is only fixed to 5 items and it loads only 1 page of a fixed 10 items. As a result, there is no way for the user to see all the data from API response with this hard-coded configuration:

https://github.com/Thieurom/NimbleSurvey/blob/5c4bb3a47eee9dec46e45bb3f5679a824a099c5a/NimbleSurvey/App/Home/HomeViewModel.swift#L76-L96

## Expect

The application could paginate to load all the surveys list data by using some kind of user inputs (swipe to the last survey item to trigger the load more action, add load next page button, etc.).

**Comment by Thieurom** [comment]
This has been implemented by PR #31

## Discussions
### My 2-cent about UX
- IMHO, the pagination loading (or loading more) should be done with the vertical scrolling, not horizontal. ([Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/controls/page-controls/) has a note on this)

  ![Screen Shot 2022-05-22 at 12 00 03](https://user-images.githubusercontent.com/17972674/169679687-4643db09-67c5-4be1-a6d7-9a288cc231aa.png)
  But by no means I'm a UX expert 😄 

### Implementation detail
- When users are at the last page, the app shows a "more" button to load more of the survey items.

  ![Simulator Screen Shot - iPhone 13 - 2022-05-22 at 11 15 51](https://user-images.githubusercontent.com/17972674/169679842-6a69f71c-6da3-43ac-8f3c-65d2dc682079.png)

- If there's an error, the app shows a toast (automatically disappears in 3 seconds) to inform the user.

  ![Simulator Screen Shot - iPhone 13 - 2022-05-22 at 11 16 20](https://user-images.githubusercontent.com/17972674/169679900-36dde730-a807-4199-b5ca-9f2a759c5c33.png)

- I used a different UI library for page control which has a flexible scrolling feature when the number of dots is large.
  
  ![Screen Shot 2022-05-22 at 12 17 00](https://user-images.githubusercontent.com/17972674/169681469-77d73581-628f-4f4f-959e-d1653fd7ca9b.png)

  However, this library does not support tapping the dots. On the simulator, we can easily use the mouse pointer to tap the dots. But on real devices, it's quite hard to tap individual dots. So I gave up on this feature (last time I checked, Apple's Weather and Instagram do not support it as well)
