### ISSUE TITLE
[Question] Usage of `Secrets.swift` concern

### ISSUE THREAD

**Issue by minhnimble** [Thieurom/NimbleSurvey#20]
## Issue

It is recognizable that in the project, after running the `make bootstrap` call, the project will create an empty `Secrets.swift` file with wrongly hard-coded values for `clientId` and `clientSecret`. Unfortunately at this point, there is no information on how to setup or get the required data to authenticate the server. Why do you choose to hide the secrets with this approach and in your opinion how the missing data should be shared for other parties?

https://github.com/Thieurom/NimbleSurvey/blob/5c4bb3a47eee9dec46e45bb3f5679a824a099c5a/NimbleSurvey/Secrets/Secrets.swift.example#L1-L3

**Comment by Thieurom** [comment]
I updated how to get, add to project the `clientId` and `clientSecret` (see PR  #33)

### Discussion
There're several ways to manage the secrets of iOS projects.

I usually see teams store them in Xcode configuration and Info.plist.
But at least we don't want to put them under version control.

One solution (that I use here) is to list them all in a file like `Secrets.swift` (again, it is not tracked by git). Also, we need to include its template version, a guide on what is needed, and how to get the required value.

If you use [CocoaPods Keys](https://github.com/orta/cocoapods-keys), you don't have to document the required secrets. It prompts you to enter every one of them when you run `pod install` or `pod update`.

Either way, in my opinion, the secrets should be kept out of code, managed, and shared amongst team members by admin or by using tools like 1Password.
